[project]
name = "displaypad-lib"
version = "0.1.1"
description = "A library to easily interact with the Mountain Displaypad"
authors = [
    {name = "AnnikenToGo",email = "anniken@annikentogo.de"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pillow (>=12.1.0,<13.0.0)",
    "displaypad-driver @ ../driver"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
